nxp-s32g: m7: update Upstream-Status to fix patch QA issue when in secure-boot-parallel building
Issue: LIN1025-3116

Update to fix typo of Upstream-Status from 'pending' to 'Pending' of internal
patch "0001-m7-sample-remove-the-code-of-enabling-CortexA53.patch", to fix the
following QA issue:
  ERROR: m7-sample-1.0-r0 do_patch: QA Issue: Malformed Upstream-Status in patch
  ...

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>