nxp-s32g: conf: update LAYERDEPENDS to fix mbedtls layer check issue
Issue: LIN1025-2269

To resolve the dependency issue where the mbedtls package from
meta-openembedded/meta-networking is required by the nxp-s32g BSP,
the 'networking-layer' needs to be added to LAYERDEPENDS. This will
address the following layer check error:
  ERROR: No recipes in default available for:
    xxx/layers/nxp-s32g/recipes-connectivity/mbedtls/mbedtls_%.bbappend

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>