optee-os/optee-test: Set a ruglar SRC_URI for them
Issue: LIN1025-8345

The previous settings broke autorebase --fetch:
ERROR: /path/to/layers/nxp-s32g/recipes-security/optee/optee-test_4.0.0.bb:
Bitbake Fetcher Error:
FetchError('Unable to fetch URL from any source.', 'git://github.com/OP-TEE/optee_test.git;branch=master;protocol=https')

The recipe should have a regular SRC_URI as other recipes. And there are
already PREFERRED_VERSION in conf/machine/nxp-s32g.conf:
PREFERRED_VERSION_optee-os ?= "4.0.0"
PREFERRED_VERSION_optee-test ?= "4.0.0"

So there is no reason to use the override.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>