nxp-s32g: add PKCS#11 HSE configuration to README
Issue: LINUXEXEC-38179

- Document required PKCS#11 HSE support settings in secure boot README
  and main README

Without these settings, building with the HSE feature fails:

  ERROR: Nothing RPROVIDES 'ccid' (but pkcs11-hse RDEPENDS on it)
  ERROR: Required build target 'pkcs11-hse' has no buildable providers.

The fix is to add CUSTOMER_RECIPES entries for ccid, opensc, pcsc-lite
and set BB_NO_NETWORK = '0' in local.conf.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>